version: "3"

services:
  spotifyd:
    image: ggoussard/spotifyd:latest
    network_mode: "host"
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "/usr/share/alsa:/usr/share/alsa"
      - "/etc/spotifyd/spotifyd.conf:/etc/spotifyd.conf"
    restart: unless-stopped
